# Description:
#   - Setup Moonbit with GitHub Actions
# REF:
#   - https://github.com/marketplace/actions/checkout

name: Code Review@Dev
on:
  pull_request_target:
    types: [opened]
  push:
    branches:
      - main

jobs:
  setup-deepseek-review:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    name: Deepseek Code Review@${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deepseek Code Review
        uses: hustcer/deepseek-review@main
        with:
          deepseek-token: ${{ secrets.DEEPSEEK_TOKEN }}
